### Numpy

### 1.Create a 1D array from a list.

In [46]:
arr_1d=[1,2,3,4,5]
print("arr_1d:",arr_1d)

arr_1d: [1, 2, 3, 4, 5]


### 2.Create a 3x3 array of zeros.

In [84]:
import numpy as np
zeros=np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### 3. Create a 2x2 array of ones.

In [121]:
ones=np.ones((2,2))
ones

array([[1., 1.],
       [1., 1.]])

### 4. Generate array from 0 to 10 (exclusive).

In [ ]:
arr = np.arange(0,11,1)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### 5. Create 5 evenly spaced numbers between 0 and 1.


In [ ]:
numbers = np.linspace(0, 1, 5)
numbers

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### 6. Create a 4x4 identity matrix.


In [157]:
identity_matrix = np.identity(4)
identity_matrix


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 7. Reshape 1D array to 2D.


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)
reshaped_arr

array([[1, 2, 3],
       [4, 5, 6]])

### 8. Get the shape and dtype of an array.


In [ ]:
arr = np.array([1.5, 7.09, 3.32, 4.67, 5.8])
print(arr.shape)
print(arr.dtype)

(5,)
float64


### 9. Reverse a NumPy array.


In [ ]:
arr = np.array([1.5, 7.09, 3.32, 4.67, 5.8])
reversed_arr = arr[::-1]
reversed_arr

array([5.8 , 4.67, 3.32, 7.09, 1.5 ])

### 10. Extract even numbers from an array.


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]) 
even_numbers = arr[arr % 2 == 0]
even_numbers 

array([2, 4, 6, 8])

### 11. Find the max in each row.


In [ ]:
arr = np.array([ 7.21, 8.34, 1.36, 9.761, 2.46, 9.76182]) 
print(arr.max(axis=0))

9.76182


### 12. Compute the mean, std, and median of an array.

In [190]:
arr=np.array([1,4,2,3,5,6,8])
print(np.mean(arr,axis=0))
print(np.std(arr,axis=0))
print(np.median(arr,axis=0))

4.142857142857143
2.2314999074019015
4.0


### 13. Stack two arrays vertically.


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.vstack((a, b))
result


array([[1, 2, 3],
       [4, 5, 6]])

### 14. Stack two arrays horizontally.


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.hstack((a, b))
result

array([1, 2, 3, 4, 5, 6])

### 15. Find the unique values and their counts.


In [ ]:
arr= np.array([1, 2, 3, 5, 1, 7, 3, 2, 9, 5])
unique_values, counts = np.unique(arr, return_counts=True)
print("Unique values:", unique_values)
print("Counts:", counts)


Unique values: [1 2 3 5 7 9]
Counts: [2 2 2 2 1 1]


### 16. Replace NaN with column means.


In [217]:
arr = np.array([
    [1, 2, np.nan, 4],
    [5, np.nan, 7, 8],
    [9, 10, 11, np.nan]
])
col_means = np.nanmean(arr, axis=0)
inds = np.where(np.isnan(arr))
arr[inds] = np.take(col_means, inds[1])
arr


array([[ 1.,  2.,  9.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11.,  6.]])

### 17. Get index of min and max values.


In [ ]:
arr = np.array([3, 7, 1, 5, 8])
min_index = np.argmin(arr)
max_index = np.argmax(arr)
print(f"Min value index: {min_index}")
print(f"Max value index: {max_index}")


Min value index: 2
Max value index: 4


### 18. Create a 3D array of random integers.


In [ ]:
arr_3d = np.random.randint(low=0, high=100, size=(3, 3, 3))
arr_3d

array([[[52, 24, 95],
        [46, 51, 45],
        [86, 17,  1]],

       [[43, 65, 20],
        [28, 27, 85],
        [67, 81, 37]],

       [[26, 92, 99],
        [54, 48,  9],
        [58, 54, 26]]], dtype=int32)

### 19. Use np.where() to replace values


In [ ]:
arr = np.array([1, 7, 3, 9, 2, 6])
new_arr = np.where(arr > 5, 10, arr)
new_arr

array([ 1, 10,  3, 10,  2, 10])

### Pandas

### 1. Create a Series using a Python list.

In [240]:
import pandas as pd
import numpy as np
my_list = [10, 20, 30, 40, 50]
series = pd.Series(my_list)
series


0    10
1    20
2    30
3    40
4    50
dtype: int64

### 2. Create a Series with custom string indices.


In [ ]:
data = [100, 200, 300, 400]
indices = ['a', 'b', 'c', 'd']
series = pd.Series(data, index=indices)
series


a    100
b    200
c    300
d    400
dtype: int64

### 3. Create a Series from a dictionary.


In [ ]:
expense_dict={'rent':2500,'grocery':3000,'travelling':2000,'insurance':5000}
expense_series=pd.Series(expense_dict)
expense_dict

{'rent': 2500, 'grocery': 3000, 'travelling': 2000, 'insurance': 5000}

### 4. Access first 3 elements of a Series.


In [ ]:
series = pd.Series([10, 20, 30, 40, 50])
elements = series[:3]
print(elements)


0    10
1    20
2    30
dtype: int64


### 5. Filter Series elements greater than 50.


In [ ]:
series = pd.Series([10, 36, 34, 79, 50.2, 91])
filtered = series[series > 50]
print(filtered)


3    79.0
4    50.2
5    91.0
dtype: float64


### 6. Add two Series with different indices.


In [ ]:
s1 = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
s2 = pd.Series([1, 2, 3], index=['b', 'c', 'd'])
result = s1 + s2
result

a     NaN
b    21.0
c    32.0
d     NaN
dtype: float64

### 7. Multiply a Series by a scalar.


In [ ]:
series = pd.Series([10, 20, 30, 40])
result = series * 2
result

0    20
1    40
2    60
3    80
dtype: int64

### 8. Use multiply() method to multiply with scalar


In [ ]:
s = pd.Series([10, 20, 30])
result = s.multiply(3)
result


0    30
1    60
2    90
dtype: int64

### 9. Sort Series by values descending


In [ ]:
s = pd.Series([30, 10, 20])
sorted_series = s.sort_values(ascending=False)
sorted_series

0    30
2    20
1    10
dtype: int64

### 10. Sort Series by index


In [ ]:
s = pd.Series([10, 20, 30], index=['b', 'c', 'a'])
sorted = s.sort_index()
sorted


a    30
b    10
c    20
dtype: int64

### 11. Check for null values


In [ ]:
s = pd.Series([10, None, 30])
null = s.isnull()
null

0    False
1     True
2    False
dtype: bool

### 12. Concatenate two Series using concat()


In [ ]:
s1 = pd.Series([1, 2])
s2 = pd.Series([3, 4])
concatenated = pd.concat([s1, s2])
concatenated

0    1
1    2
0    3
1    4
dtype: int64

### 13. Concatenate two Series using append()


In [ ]:
s1 = pd.Series([1, 2])
s2 = pd.Series([3, 4])
# appended = s1.append(s2)
# appended

### 14. Retrieve first 5 elements using .head()


In [ ]:
s = pd.Series(range(10))
first_five = s.head()
first_five


0    0
1    1
2    2
3    3
4    4
dtype: int64

### 15. Retrieve last 5 elements using .tail()


In [ ]:
s = pd.Series(range(10))
last_five = s.tail()
last_five

5    5
6    6
7    7
8    8
9    9
dtype: int64

### 16. Convert Series to DataFrame


In [ ]:
s = pd.Series([10, 20, 30])
df = s.to_frame(name='Values')
df

Values
0      10
1      20
2      30

### 17. Replace NaN with 0


In [ ]:
s = pd.Series([1, None, 3])
filled = s.fillna(0)
filled


0    1.0
1    0.0
2    3.0
dtype: float64

### 18. Drop missing values


In [ ]:
s = pd.Series([1, None, 3])
dropped = s.dropna()
dropped

0    1.0
2    3.0
dtype: float64

### 19. Check Series data type


In [ ]:
s = pd.Series([1, 2, 3])
dtype = s.dtype
dtype

dtype('int64')